INSERT INTO pessoa(nome, data_nascimento) VALUES ('Emiliano Martínez', '1992-09-02');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Geronimo Rulli', '1992-05-20');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Franco Armani', '1986-10-16');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Nahuel Molina', '1998-04-06');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Gonzalo Montiel', '1997-01-01');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Nicolás Otamendi', '1988-02-12');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Gonzalo Montiel', '1997-01-01');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Cristian Romero', '1998-04-27');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Lisandro Martínez', '1998-01-18');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Nicolás Tagliafico', '1992-08-31');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Marcos Acuña', '1991-10-28');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Juan Foyth', '1998-01-12');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Guido Rodríguez', '1994-04-12');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Rodrigo De Paul', '1994-05-24');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Exequiel Palacios', '1998-10-05');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Alexis Mac Allister', '1998-12-24');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Enzo Fernández', '2001-01-17');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Alejandro Papu Gómez', '1988-02-15');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Ángel Di María', '1988-02-14');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Leandro Paredes', '1994-06-29');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Lionel Messi', '1987-06-24');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Ángel Correa', '1995-03-09');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Lautaro Martínez', '1997-08-22');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Paulo Dybala', '1993-11-15');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Julián Álvarez', '2000-01-31');
INSERT INTO pessoa(nome, data_nascimento) VALUES ('Thiago Almada', '2001-04-26');